units:
    # Proxy Spacing Variables
    kx: U
    ky: U
    # Padding Variables
    px: U + 2
    py: U + 2
points:
    zones:
        matrix:
            columns:
                outer:
                pinky:
                    key:
                        stagger: 1.2
                ring:
                    key:
                        stagger: 6
                middle:
                    rows.mod.skip: true
                    key:
                        stagger: 4.8
                index:
                    rows.mod.skip: true
                    key:
                        stagger: -6
                inner:
                    rows.mod.skip: true
                    key:
                        stagger: -1.8
                deep_inner:
                    rows.mod.skip: true
                    rows.bottom.skip: true
                    key:
                        stagger: -1.2
            rows:
                mod:
                bottom:
                home:
                top:
                num:
        thumb_bottom:
            key:
                spread: kx
            anchor:
                ref: matrix_deep_inner_mod
                shift: [-0.6kx, -0.6ky]
                rotate: -20
            columns:
                close.key:
                    width: 1.5kx - 1
                further.key:
                    spread: kx + (0.5kx / 2)
        thumb_top:
            anchor:
                ref: thumb_bottom_close
                shift: [0.5kx, ky]
            key.spread: kx
            columns:
                close:
                further:
